# Generated by Django 6.1 on 2026-08-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0010_atividade_atividadefeita'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low', max_length=6),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atividadefeita',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.atividade', verbose_name='Atividade'),
        ),
    ]
